name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      repository-projects: write
      pull-requests: write
    steps:
      - name: checkout browser-os
        uses: actions/checkout@v4
        with:
          path: browser-os
          ref: "main"
      - name: test4
        run: |
          ls
      - name: checkout rhoffmann8.github.io
        uses: actions/checkout@v4
        with:
          repository: rhoffmann8/rhoffmann8.github.io
          path: website
          ref: "master"
          token: ${{ secrets.MY_PAT }}
      - name: Build static files
        id: build
        run: |
          cd browser-os
          ls
          npm install
          npm run build
      - name: test2
        run: |
          ls
          rm -r ./website/assets
          rm -r ./website/music
          rm ./website/Hoffmann_Resume.pdf 
          rm ./website/index.html 
          cp -r ./browser-os/dist/* ./website
          cd ./website
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "generated"
          git push
